// Disabled: job-seeker role removed from navigation. Kept for potential future re-enable.
import { useState } from 'react';
import { View } from 'react-native';
import { BackHeader, Button, Card, Chip, ConfirmSheet, DetailRow, Divider, EmptyState, Icon, Input, Logo, Screen, ScreenHeading, SectionHeader, StatusNotice, Text, TextButton, TrustBadge } from '../components';
import { jobOpportunities, type JobOpportunity, type JobSeekerProfileData } from '../data/mock';
import { colors, rhythm, size, spacing } from '../theme';

export function JobDetailScreen({ jobId, onBack, onApply }: { jobId:string; onBack:()=>void; onApply:(id:string)=>void }) {
  const job=jobOpportunities.find(item=>item.id===jobId)??jobOpportunities[0]; const [saved,setSaved]=useState(false);
  return <Screen footer={<View style={{ flexDirection:'row', gap:spacing[3] }}><Button label={saved?'Saved':'Save'} variant="secondary" fullWidth={false} style={{flex:1}} onPress={()=>setSaved(!saved)}/><Button label="Review application" fullWidth={false} style={{flex:2}} onPress={()=>onApply(job.id)}/></View>}><BackHeader onBack={onBack}/><View style={{ paddingTop:spacing[3], gap:spacing[3] }}><Logo name={job.company} size="lg"/><Text variant="heading1">{job.title}</Text><Text variant="body" tone="secondary">{job.company} · {job.city}, {job.region}</Text><TrustBadge signal={job.trust} detail="Hiring company"/><Text variant="heading3" tone="chrome">{job.salary}</Text></View><Divider tone="chrome" style={{marginTop:rhythm.sectionToSection}}/><View style={{marginTop:spacing[6],gap:spacing[3]}}><SectionHeader title="Why this matches" supporting="Based on your candidate profile"/>{job.whyItFits.map(reason=><Text key={reason} variant="body" tone="secondary">✓ {reason}</Text>)}</View><View style={{marginTop:rhythm.sectionToSection,gap:spacing[3]}}><SectionHeader title="Role"/><DetailRow label="Work type" value={job.workType}/><DetailRow label="Posted" value={job.activity}/><Text variant="body" tone="secondary">Lead daily production planning, coordinate quality checks, and keep delivery commitments visible to the floor team.</Text></View><View style={{marginTop:rhythm.sectionToSection,gap:spacing[3]}}><SectionHeader title="What they are looking for"/><Text variant="body" tone="secondary">3+ years in apparel or leather production, calm team leadership, and confident buyer coordination.</Text></View></Screen>;
}

export function ApplyFlowScreen({ jobId, onBack, onDone }: {jobId:string;onBack:()=>void;onDone:()=>void}) {
  const job=jobOpportunities.find(item=>item.id===jobId)??jobOpportunities[0]; const [submitted,setSubmitted]=useState(false); const [note,setNote]=useState('I have led production planning and quality control for leather goods teams in Kanpur.');
  if(submitted) return <Screen density="hero" scroll={false} footer={<Button label="View application" onPress={onDone}/>}><View style={{flex:1,justifyContent:'center',gap:spacing[6]}}><Icon name="check" size={size.logoLg} color={colors.semantic.success}/><View style={{gap:spacing[3]}}><Text variant="micro" tone="chrome">Application submitted</Text><Text variant="displayMedium">Your application is with {job.company}.</Text><Text variant="body" tone="secondary">We’ll notify you when the hiring team views it or changes its status.</Text></View><StatusNotice title="Submitted successfully" body={`${job.title} · Today at 10:42`} /></View></Screen>;
  return <Screen footer={<Button label="Submit application" onPress={()=>setSubmitted(true)}/>}><BackHeader title="Review application" onBack={onBack}/><ScreenHeading title="Review before applying" supporting="The company will receive your public candidate profile and the details below."/><View style={{marginTop:rhythm.titleToContent,gap:spacing[3]}}><Card><Text variant="heading3">{job.title}</Text><Text variant="bodySmall" tone="secondary">{job.company} · {job.city}</Text></Card><SectionHeader title="Profile shared"/><DetailRow label="Candidate" value="Aarav Sharma"/><DetailRow label="Resume" value="Aarav-Sharma-resume.pdf"/><DetailRow label="Availability" value="30 days"/><Input label="Note to hiring team" value={note} onChangeText={setNote} multiline optional/><Text variant="bodySmall" tone="tertiary">You can withdraw later, but the company may retain information already reviewed.</Text></View></Screen>;
}

export function SavedJobsScreen({onBack,onOpenJob}:{onBack:()=>void;onOpenJob:(id:string)=>void}) { const [jobs,setJobs]=useState(jobOpportunities.slice(0,2)); return <Screen><BackHeader title="Saved jobs" onBack={onBack}/><ScreenHeading title="Saved jobs" supporting="Roles you want to revisit before applying."/><View style={{marginTop:rhythm.titleToContent,gap:spacing[3]}}>{jobs.map(job=><View key={job.id}><JobCard job={job} onPress={()=>onOpenJob(job.id)}/><TextButton label="Remove from saved" tone="danger" onPress={()=>setJobs(current=>current.filter(item=>item.id!==job.id))}/></View>)}{jobs.length===0?<EmptyState title="No saved jobs." body="Save a role from its detail page and it will appear here." actionLabel="Find jobs" onAction={onBack}/>:null}</View></Screen>; }

function JobCard({job,onPress}:{job:JobOpportunity;onPress:()=>void}) { return <Card accessibilityLabel={`${job.title} at ${job.company}`} onPress={onPress}><View style={{flexDirection:'row',gap:spacing[3]}}><Logo name={job.company} size="md"/><View style={{flex:1,gap:spacing[1]}}><Text variant="heading3">{job.title}</Text><Text variant="bodySmall" tone="secondary">{job.company} · {job.city}</Text><Text variant="bodySmall" tone="chrome">{job.salary}</Text></View><Icon name="chevronRight" color={colors.text.tertiary}/></View></Card>; }

export function ApplicationDetailScreen({onBack,onOpenConversation}:{onBack:()=>void;onOpenConversation:()=>void}) { const [withdraw,setWithdraw]=useState(false); const [withdrawn,setWithdrawn]=useState(false); return <Screen><BackHeader title="Application" onBack={onBack}/><View style={{paddingTop:spacing[4],gap:spacing[2]}}><Text variant="heading1">Production Supervisor</Text><Text variant="body" tone="secondary">ABC Leather Works · Kanpur</Text><Text variant="micro" tone={withdrawn?'tertiary':'chrome'}>{withdrawn?'Withdrawn':'Interview requested'}</Text></View>{withdrawn?<View style={{marginTop:spacing[5]}}><StatusNotice title="Application withdrawn" body="The hiring team can no longer progress this application." tone="warning"/></View>:null}<View style={{marginTop:rhythm.sectionToSection,gap:spacing[4]}}><SectionHeader title="Status timeline"/><Timeline title="Application submitted" detail="Today · 09:18" active/><Timeline title="Profile viewed" detail="Today · 11:42" active/><Timeline title="Interview requested" detail="Tomorrow afternoon · Reply to confirm" active={!withdrawn}/><Timeline title="Decision" detail="Waiting for hiring team"/></View><View style={{marginTop:rhythm.sectionToSection,gap:spacing[3]}}><Button label="Message company" onPress={onOpenConversation} disabled={withdrawn}/><Button label="Withdraw application" variant="destructive" onPress={()=>setWithdraw(true)} disabled={withdrawn}/></View><ConfirmSheet visible={withdraw} eyebrow="Destructive action" title="Withdraw this application?" body="ABC Leather Works will be notified and you cannot undo this action." confirmLabel="Withdraw application" destructive onClose={()=>setWithdraw(false)} onConfirm={()=>{setWithdraw(false);setWithdrawn(true)}}/></Screen>; }
function Timeline({title,detail,active=false}:{title:string;detail:string;active?:boolean}) { return <View style={{flexDirection:'row',gap:spacing[3]}}><View style={{width:12,height:12,borderRadius:6,marginTop:4,backgroundColor:active?colors.chrome[200]:colors.surface.selected,borderWidth:1,borderColor:colors.border.strong}}/><View style={{flex:1,gap:spacing[1]}}><Text variant="body" tone={active?'primary':'secondary'}>{title}</Text><Text variant="bodySmall" tone="tertiary">{detail}</Text></View></View>; }

export function CandidateProfileEditorScreen({profile,previewOnly=false,onBack,onPreview,onSave}:{profile?:JobSeekerProfileData|null;previewOnly?:boolean;onBack:()=>void;onPreview?:()=>void;onSave?:(profile:JobSeekerProfileData)=>void}) { const [name,setName]=useState(profile?.fullName??'Aarav Sharma'); const [headline,setHeadline]=useState(profile?.headline??'Production and sourcing professional'); const [city,setCity]=useState(profile?.city??'Kanpur'); const [summary,setSummary]=useState('Production professional with four years of experience coordinating leather goods teams, quality checks, and buyer commitments.'); if(previewOnly) return <Screen><BackHeader title="Public candidate preview" onBack={onBack}/><View style={{paddingTop:spacing[5],gap:spacing[3]}}><Logo name={name} size="xl"/><Text variant="heading1">{name}</Text><Text variant="body" tone="secondary">{headline} · {city}</Text><TrustBadge signal="verified" detail="Email verified"/></View><Divider tone="chrome" style={{marginTop:rhythm.sectionToSection}}/><View style={{marginTop:spacing[6],gap:spacing[3]}}><SectionHeader title="Profile"/><Text variant="body" tone="secondary">{summary}</Text></View><View style={{marginTop:rhythm.sectionToSection,gap:spacing[3]}}><SectionHeader title="Skills"/><View style={{flexDirection:'row',flexWrap:'wrap',gap:spacing[2]}}>{['Production planning','Quality control','Buyer coordination'].map(skill=><Chip key={skill} label={skill}/>)}</View></View><StatusNotice title="Preview mode" body="This is what verified hiring businesses can review." tone="warning"/></Screen>; return <Screen footer={<Button label="Save candidate profile" onPress={()=>onSave?.({...profile!,fullName:name,headline,city,email:profile?.email??'candidate@binder.test',professionId:profile?.professionId??'manufacturing-production',skillIds:profile?.skillIds??[],desiredRoleIds:profile?.desiredRoleIds??[],emailVerified:true})}/>}><BackHeader title="Edit candidate profile" onBack={onBack} action={<TextButton label="Preview" onPress={onPreview}/>} /><ScreenHeading title="Candidate profile" supporting="Keep the information hiring teams see accurate and specific."/><View style={{marginTop:spacing[8],gap:spacing[5]}}><Input label="Full name" value={name} onChangeText={setName}/><Input label="Professional headline" value={headline} onChangeText={setHeadline}/><Input label="City" value={city} onChangeText={setCity}/><Input label="Professional summary" value={summary} onChangeText={setSummary} multiline/><SectionHeader title="Skills"/><View style={{flexDirection:'row',flexWrap:'wrap',gap:spacing[2]}}>{['Production planning','Quality control','Buyer coordination'].map(skill=><Chip key={skill} label={skill} selected/>)}</View></View></Screen>; }

export function CandidateDocumentsScreen({onBack}:{onBack:()=>void}) { const [resume,setResume]=useState('Aarav-Sharma-resume.pdf'); return <Screen><BackHeader title="Resume & experience" onBack={onBack}/><ScreenHeading title="Resume and history" supporting="Manage the evidence hiring teams receive with an application."/><View style={{marginTop:rhythm.titleToContent,gap:spacing[3]}}><SectionHeader title="Resume"/>{resume?<Card><Text variant="body">{resume}</Text><Text variant="bodySmall" tone="tertiary">Updated 28 Aug 2026 · 1.2 MB</Text><TextButton label="Remove" tone="danger" onPress={()=>setResume('')}/></Card>:<EmptyState title="No resume uploaded." body="Add a PDF resume before applying to roles."/>}<Button label={resume?'Replace resume':'Upload resume'} variant="secondary" icon={<Icon name="upload"/>} onPress={()=>setResume('Aarav-Sharma-resume.pdf')}/></View><HistorySection title="Work history" rows={['Production Coordinator · Roshan Clothing · 2022–Present','Quality Assistant · Northline Tanners · 2020–2022']}/><HistorySection title="Education" rows={['B.Com · CSJM University · 2020']}/><HistorySection title="Other documents" rows={['Production planning certificate.pdf']}/></Screen>; }
function HistorySection({title,rows}:{title:string;rows:string[]}) { return <View style={{marginTop:rhythm.sectionToSection,gap:spacing[2]}}><SectionHeader title={title} action="Add"/>{rows.map(row=><View key={row}><Text variant="body" style={{paddingVertical:spacing[3]}}>{row}</Text><Divider/></View>)}</View>; }
